
# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile
analytics:
  target: ci
  outputs:
    ci:
      type: postgres
      host: '${HOST_NAME}'
      user: '${USERNAME}'
      pass: '${PASSWORD}'
      port: 5432
      dbname: '${DBNAME}'
      schema: '${CISCHEMA}'
      threads: 1
      keepalives_idle: 300 # default 0, indicating the system default
      search_path: "staging"
    prod:
      type: postgres
      host: '${HOST_NAME}'
      user: '${USERNAME}'
      pass: '${PASSWORD}'
      port: 5432
      dbname: '${DBNAME}'
      schema: '${PRODSCHEMA}'
      threads: 1
      keepalives_idle: 300 # default 0, indicating the system default
      search_path: "staging"

config:
    send_anonymous_usage_stats: False
