name: Build Status
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DBT_PROFILES_DIR: ./
  HOST_NAME: ${{secrets.HOST_NAME}}
  USERNAME: ${{secrets.USERNAME}}
  PASSWORD: ${{secrets.PASSWORD }}
  DBNAME: ${{secrets.DBNAME}}
  CISCHEMA: ${{secrets.CISCHEMA}}
  PRODSCHEMA: ${{secrets.PRODSCHEMA}}
  NETLIFY_AUTH_TOKEN: "${{secrets.NETLIFY_AUTH_TOKEN}}"
  NETLIFY_SITE_ID: "{{secrets.NETLIFY_SITE_ID}}"

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out the repository code
        uses: actions/checkout@v2


      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"


      - name: Install Poetry and dependencies
        run: |
          python3.7 -m pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --no-dev


      - name: Install dbt dependencies
        run: dbt deps


      - name: Run debug to check for connectivity issues
        run: dbt debug


      - name: Run tests against sources only
        run: dbt test -t ci --exclude example


      - name: Run DBT against staging
        run: dbt run -t ci


      - name: Run tests against models only
        run: dbt test -t ci --models example


      - name: Deploy to production
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          dbt run -t prod
          dbt test -t prod


      - name: Build Docs
        run: dbt docs generate


      - name: show target
        run: ls ./target


      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.0
        with:
          publish-dir: './target'
          # production-branch: master
          # github-token: ${{secrets.GITHUB_TOKEN}}
          # deploy-message: "Deploy from GitHub Actions"
